### PR TITLE
Handling fork/clone

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/2)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[doc/generated/libsyscall_intercept.3, line 105 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn2yVOqt_lKHWW8pRb:-Kjn2yVPMmLfuIRHfAmE:b-22kpsa) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/doc/generated/libsyscall_intercept.3#L105)):*
> ```Roff
> .fi
> .PP
> Using \f[C]intercept_hook_point_clone_child\f[], one can be notified of
> ```

s/one can be notified of thread creations/one can be notified of 

---

*[examples/fork_ban.c, line 35 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn3kdk9fy1FtYVmsm_:-Kjn3kdk9fy1FtYVmsma:bh9m6o2) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L35)):*
> ```C
> /*
>  * fork_ban.c - Block forking new processes after a maximum number of
>  *  forks.
> ```

Extra space after *'. 

---

*[examples/fork_ban.c, line 53 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn40bD0I2lev9ksEoI:-Kjn40bD0I2lev9ksEoJ:b26982h) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L53)):*
> ```C
>  *
>  * The second argument of a clone syscall specifies the
>  * top of a stack area for the new child thrad/process.
> ```

s/thrad/thread

---

*[examples/fork_ban.c, line 125 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4OwHR6W2nz8GbDkk:-Kjn4OwHR6W2nz8GbDkl:b-43p446) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L125)):*
> ```C
> 
> 	if (fork_counter >= fork_counter_max) {
> 		static const char msg[] = "fork not allowed anymore!\n";
> ```

s/fork not allowed anymore/fork count has exceeded maximum.  (Or something like that)

---

*[examples/fork_ban.c, line 151 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4cPHWFaoHNFGSNE9:-Kjn4cPHWFaoHNFGSNEA:boigzca) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L151)):*
> ```C
> 		fork_counter_max = atoi(e);
> 	else
> 		fork_counter_max = 16;
> ```

I know this is an example but I would #define the fork_counter_max default value.

---

*[include/libsyscall_intercept_hook_point.h, line 60 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4rpTf4Vl5kTJImYk:-Kjn4rpTf4Vl5kTJImYl:bn00laf) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/include/libsyscall_intercept_hook_point.h#L60)):*
> ```objc
> 			long *result);
> 
> extern long (*intercept_hook_point_clone_child)(void);
> ```

Why is the return value of this a instead of an int?

---

*[src/intercept.c, line 332 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn5bgqdlT8ceAmUwK0:-Kjn5bgqdlT8ceAmUwK1:b-xjyx4s) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept.c#L332)):*
> ```C
> 		/*
> 		 * The clone syscall's arg1 is a pointer to a memory region
> 		 * that servers as the stack space of a new child thread.
> ```

s/servers/serves

---

*[src/intercept.c, line 364 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn7glHECdwqazMFbR0:-Kjn7glHECdwqazMFbR1:ba63p1z) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept.c#L364)):*
> ```C
>  *
>  * It is a very bad idea to return a non-zero value from here. But a hook
>  * function is allowed to do that, just in case.
> ```

Why are you allowing a non-zero return at all?

---

*[src/intercept_template.s, line 339 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn8-IUsEDZpCkaf9qO:-Kjn8-IUsEDZpCkaf9qP:b624hre) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept_template.s#L339)):*
> ```
> 
> 	/*
> 	 * Fix the alignmetn if needed. The C functions called
> ```

s/alignmetn/alignment

---

*[src/intercept_template.s, line 363 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn9ku_OTmQw0LcAerZ:-Kjn9ku_OTmQw0LcAer_:bihp0v6) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept_template.s#L363)):*
> ```
> 	pushq       %r11 /* rsp_in_asm_wrapper */
> 
> 	leaq        L7(%rip), %r11
> ```

Why are you automatically pushing the calculated return address for the clone_wrapper on the stack?  Shouldn't it be a conditional?

---

*[test/test_clone_thread_preload.c, line 60 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-KjnBhxvPaAEzc4k3O_b:-KjnBhxvPaAEzc4k3O_c:bf2a9wb) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/test/test_clone_thread_preload.c#L60)):*
> ```C
> 	long *result)
> {
> 	(void) arg1;
> ```

arg1 is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/2)*

**Comment by GBuella** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[examples/fork_ban.c, line 151 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4cPHWFaoHNFGSNE9:-KjnPQRvsQfb5T9z5oAk:boba8rk) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L151)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

I know this is an example but I would #define the fork_counter_max default value.
</blockquote></details>

What would be the name of the macro?

---

*[include/libsyscall_intercept_hook_point.h, line 60 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4rpTf4Vl5kTJImYk:-KjnQBopopBXRcKtGeSF:b8infi2) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/include/libsyscall_intercept_hook_point.h#L60)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why is the return value of this a instead of an int?
</blockquote></details>

The long just represents the 64 bit value of a syscall.
Following this function signature:
http://man7.org/linux/man-pages/man2/syscall.2.html 
`long syscall(long number, ...);`
I think it is `long` on pretty much any platform here Linux as available.

---

*[src/intercept.c, line 364 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn7glHECdwqazMFbR0:-KjnR6bRGFhbqUZvkpXD:b-wj4ht6) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept.c#L364)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why are you allowing a non-zero return at all?
</blockquote></details>

I don't know, any reason for not allowing it?
Allowing it doesn't cost us anything, and what a user wants to use it for is none of my business.

---

*[src/intercept_template.s, line 363 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn9ku_OTmQw0LcAerZ:-KjnRnBpsELSkYf1daJ6:b-ehurx3) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept_template.s#L363)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why are you automatically pushing the calculated return address for the clone_wrapper on the stack?  Shouldn't it be a conditional?
</blockquote></details>

It is so much simpler this way.
For example, if the code would not always push all the arguments, then the size of stack area used would depend on how many arguments are actually pushed. Which would affect the alignment, making it even more difficult to make sure rsp becomes 16 byte aligned. Well, it is very easy to do for a compiler, but tedious in hand written assembly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/2)*

**Comment by GBuella** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[doc/generated/libsyscall_intercept.3, line 105 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn2yVOqt_lKHWW8pRb:-KjnVUrObSsLJgX7pySI:b-rsr6gx) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/doc/generated/libsyscall_intercept.3#L105)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

s/one can be notified of thread creations/one can be notified of 
</blockquote></details>

That would leave "notified of easily". Is that a typo?

---

*[examples/fork_ban.c, line 35 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn3kdk9fy1FtYVmsm_:-KjnVfu_rDVKs0WtCkdo:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L35)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Extra space after *'. 
</blockquote></details>

Done.

---

*[examples/fork_ban.c, line 53 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn40bD0I2lev9ksEoI:-KjnVgsJqTQsvbVX_CJP:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L53)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

s/thrad/thread
</blockquote></details>

Done.

---

*[examples/fork_ban.c, line 125 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4OwHR6W2nz8GbDkk:-KjnVif13qOC_CluLb3u:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L125)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

s/fork not allowed anymore/fork count has exceeded maximum.  (Or something like that)
</blockquote></details>

Done.

---

*[src/intercept.c, line 332 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn5bgqdlT8ceAmUwK0:-KjnVjQhcJIWfiFTb3s_:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept.c#L332)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

s/servers/serves
</blockquote></details>

Done.

---

*[src/intercept_template.s, line 339 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn8-IUsEDZpCkaf9qO:-KjnVkBRtjpbkg-iAEYw:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept_template.s#L339)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

s/alignmetn/alignment
</blockquote></details>

Done.

---

*[test/test_clone_thread_preload.c, line 60 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-KjnBhxvPaAEzc4k3O_b:-KjnVT77l4NeKbWHxaZz:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/test/test_clone_thread_preload.c#L60)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

arg1 is used.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/2)*

**Comment by GBuella** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[include/libsyscall_intercept_hook_point.h, line 60 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4rpTf4Vl5kTJImYk:-KjnVz_6hM9KTHMDyLOe:b5ae1yn) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/include/libsyscall_intercept_hook_point.h#L60)):*
> 64 bit value of a syscall.
I mean the 64 bit return value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/2)*

**Comment by sarahjelinek** [comment]
Review status: 0 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[doc/generated/libsyscall_intercept.3, line 105 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn2yVOqt_lKHWW8pRb:-KjoHFMggE_yu3MaTgmT:brkzun4) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/doc/generated/libsyscall_intercept.3#L105)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

That would leave "notified of easily". Is that a typo?
</blockquote></details>

Sorry. Meant to delete this comment. Please ignore.

---

*[examples/fork_ban.c, line 151 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4cPHWFaoHNFGSNE9:-KjoHS6DMdboMIqHaZEL:b-twvxtu) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L151)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

What would be the name of the macro?
</blockquote></details>

#define FORK_MAX_COUNT

---

*[src/intercept.c, line 364 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn7glHECdwqazMFbR0:-KjoH_t7g6ZRtmiK_Ydv:b-8uhc6q) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept.c#L364)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

I don't know, any reason for not allowing it?
Allowing it doesn't cost us anything, and what a user wants to use it for is none of my business.
</blockquote></details>

Yeah, I am worried that we are going to let the user hang themselves. I think if it is bad thing and not generally accepted we should disallow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/2)*

**Comment by GBuella** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/fork_ban.c, line 151 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn4cPHWFaoHNFGSNE9:-KjqxQaGi9CMu5CXdk01:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/examples/fork_ban.c#L151)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

#define FORK_MAX_COUNT
</blockquote></details>

Done.

---

*[src/intercept.c, line 364 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-Kjn7glHECdwqazMFbR0:-KjqxRlewAZ5Twz3D8TS:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/f7b33d39d67247b1b997b35f189bd7233be8a980/src/intercept.c#L364)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Yeah, I am worried that we are going to let the user hang themselves. I think if it is bad thing and not generally accepted we should disallow.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/2)*

**Comment by sarahjelinek** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/2#-:-KjsxG-UAwJqbhiK4FtL:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 10 of 17 files at r1, 1 of 5 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/2)*

**Pull request merged**
