### PR TITLE
Remove usage of /proc/self/cmdline

### PR DESCRIPTION
**Pull request by GBuella**
There is no need for opening, reading, closing a file for checking the command line used to start the process.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/41)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41)*

**Comment by marcinslusarz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/entry.c, line 89 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/41#-KreUuQjFXljOoodeeeu:-KreUuQjFXljOoodeeev:bkvuxwx) ([raw file](https://github.com/pmem/syscall_intercept/blob/39857b9d81d8ee3d17ec1cd5f1b5deb0d38027c0/src/entry.c#L89)):*
> ```C
> 	 * "./somewhere/a.out" matches "a.out"
> 	 * "./a.out" matches "a.out"
> 	 * "./xa.out" does not match "a.out"
> ```

Please add test for this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41)*

**Comment by GBuella** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/entry.c, line 89 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/41#-KreUuQjFXljOoodeeeu:-KreuydPyNfgK7bFSDD1:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/39857b9d81d8ee3d17ec1cd5f1b5deb0d38027c0/src/entry.c#L89)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please add test for this case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41)*

**Comment by krzycz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/CMakeLists.txt, line 186 at r2](https://reviewable.io:443/reviews/pmem/syscall_intercept/41#-KrpPWdCKu9NQm5KeP0V:-KrpPWdCKu9NQm5KeP0W:b8u4ogl) ([raw file](https://github.com/pmem/syscall_intercept/blob/2308a03f4fecb36ba96a8ac5cd3c8edb5f12b121/test/CMakeLists.txt#L186)):*
> ```CMake
> 	PROPERTIES PASS_REGULAR_EXPRESSION "disallowed")
> 
> # the filter is a substring of the executable name
> ```

How is this one different from the one below? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/CMakeLists.txt, line 186 at r2](https://reviewable.io:443/reviews/pmem/syscall_intercept/41#-KrpPWdCKu9NQm5KeP0V:-Krp_K45W6SMgL96pAD6:b-ypukjc) ([raw file](https://github.com/pmem/syscall_intercept/blob/2308a03f4fecb36ba96a8ac5cd3c8edb5f12b121/test/CMakeLists.txt#L186)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

How is this one different from the one below? 
</blockquote></details>

This one tests:
`cmdline = "/home/joe/a.out"  filter = "ut"` (where "ut" is a substring of "a.out")
The one below tests:
`cmdline = "/home/joe/a.out"  filter = "xa.out"` (where "a.out" is a substring of "xa.aout")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/entry.c, line 111 at r2](https://reviewable.io:443/reviews/pmem/syscall_intercept/41#-KscnG6cfPuLxv99kUwh:-KscnG6cfPuLxv99kUwi:bdncgje) ([raw file](https://github.com/pmem/syscall_intercept/blob/44327d2d9894268dedc2cff151cb289096f9d288/src/entry.c#L111)):*
> ```C
> 
> 	fd = (int)syscall_no_intercept(SYS_open,
> 			"/proc/self/cmdline", O_RDONLY, (mode_t)0);
> ```

You need to update README to reflect that you no longer parse /proc/self/cmdline since it's part of the arg in the entry_point() constructor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41)*

**Comment by GBuella** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/entry.c, line 111 at r2](https://reviewable.io:443/reviews/pmem/syscall_intercept/41#-KscnG6cfPuLxv99kUwh:-KsdILw7TUAJXXB9zNDQ:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/44327d2d9894268dedc2cff151cb289096f9d288/src/entry.c#L111)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

You need to update README to reflect that you no longer parse /proc/self/cmdline since it's part of the arg in the entry_point() constructor.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/41#-:-KsdiUBpYZlb5mr7-830:bnfp4nl)*

**Pull request merged**
