### PR TITLE
more verbose logging in should_patch_object

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/34)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/34#-:-KoHg5WPEjEoGFHeXjt6:bnfp4nl)*

**Comment by marcinslusarz** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/34)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/34#-:-KoIttNToM7eaq9s3pPl:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/34#-:-KoiGj3k-MSH5oiLADVs:bnfp4nl)*

**Pull request merged**
