### PR TITLE
logging example -- fix a typo in a condition

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/60)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/60)*

**Comment by krzycz** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/60#-:-Ku0mpzsocRnCaQTaTFt:bnfp4nl)*

**Comment by marcinslusarz** [comment]
Maybe worth stating in commit description it was reported by Coverity? :D

**Comment by GBuella** [comment]
> stating in commit description it was reported by Coverity

Done

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/60#-:-Ku4Xa3HrLNv5xVQBMC5:bnfp4nl)*

**Pull request merged**
