### PR TITLE
Logging continued

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/38)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/syscall_logger.c, line 146 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/38#-KpnPkF4YT-MirCzyQt2:-KpnPkF4YT-MirCzyQt3:b87tfa7) ([raw file](https://github.com/pmem/syscall_intercept/blob/498596c2ae8e6481abf1f14e52d8257052b718be/examples/syscall_logger.c#L146)):*
> ```C
> 	} else {
> 		*dst++ = '-';
> 		nu = ((unsigned long)((0l - 1l) - n)) + 1lu;
> ```

It would be more readable if you replace "l" with "L".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/38)*

**Comment by krzycz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/38#-:-KpnQJJSuOrNRTdSqL6h:bnfp4nl)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/syscall_logger.c, line 146 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/38#-KpnPkF4YT-MirCzyQt2:-Kpq5bcQ02fxkZp5Iexs:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/8403c49f7ddfbb5b811fcd3eec7036cae228a264/examples/syscall_logger.c#L146)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

It would be more readable if you replace "l" with "L".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/38)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/38#-:-KqY5tG9fMnwuggqiTsX:bnfp4nl)*

**Pull request merged**
