### PR TITLE
Handling fork/clone

### PR DESCRIPTION
**Pull request by GBuella**
PR to master

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/8)

### CODE REVIEW

**Comment by krzycz** [comment]
That's cool, man!
:lgtm_strong: 

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/fork_ban.c, line 37 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/8#-Kjxzx1kLsX-vVy-j2e5:-Kjxzx1kLsX-vVy-j2e6:b5pkzzo) ([raw file](https://github.com/pmem/syscall_intercept/blob/dfdbe7ba43add95917a4088053c8d17bfe5f52c7/examples/fork_ban.c#L37)):*
> ```C
>  * forks.
>  * This library demonstrates a way to handle fork syscalls. In contrast
>  * with thread creation (for an example see test/test_clone_thread_preload.c)
> ```

in contrast to...?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/8#-:-Kjy0tOE1Uo_rHUTqD_d:b-yhqodw)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/fork_ban.c, line 37 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/8#-Kjxzx1kLsX-vVy-j2e5:-Kjy7uKJjPmU-NUdSau0:b-inflbi) ([raw file](https://github.com/pmem/syscall_intercept/blob/dfdbe7ba43add95917a4088053c8d17bfe5f52c7/examples/fork_ban.c#L37)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

in contrast to...?
</blockquote></details>

I'm going to change it.
https://english.stackexchange.com/questions/249928/difference-between-in-contrast-to-and-in-contrast-with

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/8)*

**Comment by GBuella** [comment]
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/fork_ban.c, line 37 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/8#-Kjxzx1kLsX-vVy-j2e5:-Kk1QmRrIldTXHUb4abv:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/dfdbe7ba43add95917a4088053c8d17bfe5f52c7/examples/fork_ban.c#L37)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

I'm going to change it.
https://english.stackexchange.com/questions/249928/difference-between-in-contrast-to-and-in-contrast-with
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/8)*

**Comment by sarahjelinek** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/8#-:-KkCN2kzojypuRsC6dPs:bnfp4nl)*

**Pull request merged**
