### PR TITLE
Fix static library

### PR DESCRIPTION
**Pull request by GBuella**
The static library libsyscall_intercept.a just could not be used at all.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/44)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/44)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/44)*

**Comment by sarahjelinek** [comment]
Reviewed 1 of 9 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/44)*

**Comment by GBuella** [comment]
I added partial linking to the build process (as is done in NVML as well). Following this, there is a single object file used for both the shared and static libraries.
But now moving around the library constructor is not needed, so I think I can revert the file renaming and what-not.

**Comment by krzycz** [comment]
Reviewed 1 of 9 files at r1, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/44)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CMakeLists.txt, line 108 at r4](https://reviewable.io:443/reviews/pmem/syscall_intercept/44#-KstCPQXwZLeSIQgf1Ea:-KstCPQXwZLeSIQgf1Eb:bbim2cf) ([raw file](https://github.com/pmem/syscall_intercept/blob/468f0aa8ab12e84e171f2545867cf7c5bf9a23a5/CMakeLists.txt#L108)):*
> ```CMake
> 	OUTPUT syscall_intercept_scoped.o
> 	COMMAND ${CMAKE_LINKER}
> 		-r --whole-archive ${syscall_intercept_unscoped_a}
> ```

CMAKE_LINKER?  Same comment as for static libs in pmemfile. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/44)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 108 at r4](https://reviewable.io:443/reviews/pmem/syscall_intercept/44#-KstCPQXwZLeSIQgf1Ea:-KstcVN0gOkoCez1i_7v:buyqln1) ([raw file](https://github.com/pmem/syscall_intercept/blob/468f0aa8ab12e84e171f2545867cf7c5bf9a23a5/CMakeLists.txt#L108)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

CMAKE_LINKER?  Same comment as for static libs in pmemfile. 
</blockquote></details>

Same response as for static libs in pmemfile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/44)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/44#-:-KtNzfOkoRBnbgJSvrrU:bnfp4nl)*

**Pull request merged**
