### PR TITLE
Add information in readme about discontinuation of the project

### PR DESCRIPTION
**Pull request by szadam**
Preview: https://github.com/szadam/syscall_intercept/blob/master/README.md

### CODE REVIEW

**Review by lukaszstolarczuk — APPROVED** [review]

**Review by pbalcer — COMMENTED** [review]
This repo is now being maintained by @en4bz. We should not be archiving it.

**Comment by lukaszstolarczuk** [comment]
@pbalcer, yeah, that was my concern - should we then update our blog?

// https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/

**Comment by en4bz** [comment]
Do you want to transfer it to @vmware?

**Comment by pbalcer** [comment]
That's up to you. I just gave you admin permissions to this repo so you should be able to [transfer it](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization). But I'm also ok with leaving it in the pmem org if that's less hassle.

@lukaszstolarczuk sure, you can update the blog post.

**Comment by lukaszstolarczuk** [comment]
Sure can do! It's good to hear this repo found a new home 😉 

// Updated:
FYI, done in https://github.com/pmem/pmem.github.io/pull/332

**Comment by lukaszstolarczuk** [comment]
@en4bz, as I added in the comment above, we'll be updating info in our blog post about discontinuation from our side.

Two thoughts from me:
1. Perhaps you can add some contact information in the Readme file on this repo, if you feel like it, of course.
2. Should we point (in our blog post) some/your contact information?

**Pull request closed without merging**
