### PR TITLE
Ability to patch all loaded object files

### PR DESCRIPTION
**Pull request by GBuella**
#7

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/9)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 19 of 20 files at r1.
Review status: 18 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/9)*

**Comment by GBuella** [comment]
For those who feel like some more explanation would be appropriate, it is going on in this PR is coming soon:

https://github.com/GBuella/syscall_intercept/blob/patch_all_objs_2/hacking.md

That hacking.md is going to describe things in greater detail, but it still needs some days to be written, so I plan to add it in another PR.

**Comment by krzycz** [comment]
Reviewed 1 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/9)*

**Comment by krzycz** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/9#-:-Kkz483uLNl0FFTIv1RD:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 20 of 20 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/9)*

**Pull request merged**
