### PR TITLE
Refactor intercept template

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/47)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
Reviewed 4 of 15 files at r1.
Review status: 4 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/intercept.c, line 597 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-Ktmt03gsux8w9JHOmOA:-Ktmt03gsux8w9JHOmOB:bm97dob) ([raw file](https://github.com/pmem/syscall_intercept/blob/3baec966acb8623561c3ba538c3f678bc2fd3f45/src/intercept.c#L597)):*
> ```C
> 	struct patch_desc *patch = context->patch_desc;
> 
> 	get_syscall_in_context(context, &desc);
> ```

Add comment above this call just to explain what 'in_context' means.

---

*[src/intercept_template.s, line 213 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KtmvrYxI0_QhwgP03JH:-KtmvrYxI0_QhwgP03JI:b5vl6es) ([raw file](https://github.com/pmem/syscall_intercept/blob/6fbb0153d0e9c2d89d325ae77dc720bea1c1a94a/src/intercept_template.s#L213)):*
> ```
>  * 16n + 8 bytes of stack is used ( when the original RSP is just 8 bytes
>  * aligned ). An address in the appropriate function is used as the faked
>  * return address pushed on the stack before calling the C function.
> ```

Where did all of these comments go? I assume they are still applicable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47)*

**Comment by sarahjelinek** [comment]
Review status: 4 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/intercept_template.s, line 213 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KtmvrYxI0_QhwgP03JH:-KtmzmwfpNzLlpLrC3oy:b-f9ixkg) ([raw file](https://github.com/pmem/syscall_intercept/blob/6fbb0153d0e9c2d89d325ae77dc720bea1c1a94a/src/intercept_template.s#L213)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Where did all of these comments go? I assume they are still applicable?
</blockquote></details>

These changes to intercept_template.s are really large. Perhaps we can talk through them so I understand how the new code works and why you were able to refactor out so much of the old code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47)*

**Comment by krzycz** [comment]
Reviewed 14 of 15 files at r1.
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47)*

**Comment by GBuella** [comment]
FYI: I plan to add more text to `asm_wrapper.md`, so I might force push that.
I don't plan to change the code (other what is asked in review), so that can be rewieved.

**Comment by GBuella** [comment]
Review status: 7 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/intercept_template.s, line 213 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KtmvrYxI0_QhwgP03JH:-Ku4_WmSYSQFtGwzNq1_:b-85t1g8) ([raw file](https://github.com/pmem/syscall_intercept/blob/6fbb0153d0e9c2d89d325ae77dc720bea1c1a94a/src/intercept_template.s#L213)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

These changes to intercept_template.s are really large. Perhaps we can talk through them so I understand how the new code works and why you were able to refactor out so much of the old code.
</blockquote></details>

See asm_wrapper.md

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47)*

**Comment by GBuella** [comment]
Review status: 7 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/intercept.c, line 597 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-Ktmt03gsux8w9JHOmOA:-Ku4bX8Ap6C5bbffL510:b-bi0hu) ([raw file](https://github.com/pmem/syscall_intercept/blob/3baec966acb8623561c3ba538c3f678bc2fd3f45/src/intercept.c#L597)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Add comment above this call just to explain what 'in_context' means.
</blockquote></details>

Done.
Added comments to the definition of the get_syscall_in_context function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47)*

**Comment by sarahjelinek** [comment]
Reviewed 1 of 6 files at r3.
Review status: 8 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/asm_wrapper.md, line 8 at r3](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KuMl9MPxnMwA_mQ4dpb:-KuMl9MQZIKAcqnG6kTO:bs4hz2s) ([raw file](https://github.com/pmem/syscall_intercept/blob/6a197f508cf6434c82ef573dd4e570185553f720/src/asm_wrapper.md#L8)):*
> ```Markdown
> 
>   One can not issue a jump from the place of a patched syscall instruction
> to C function, due perky ABI details. This is simply not supported, and is
> ```

do you mean to say 'due to pesky ABI details'? 

---

*[src/asm_wrapper.md, line 23 at r3](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KuMlXkMrcfM0NjYIPNJ:-KuMlXkMrcfM0NjYIPNK:b-8pehqm) ([raw file](https://github.com/pmem/syscall_intercept/blob/6a197f508cf6434c82ef573dd4e570185553f720/src/asm_wrapper.md#L23)):*
> ```Markdown
> jumps jump to different places, this can be used to infer the origin of those
> jumps. The code in [intercept_template.s](intercept_template.s) serves
> this purpuse. Different instances are generated from this template to
> ```

s/purpuse/purpose

---

*[src/asm_wrapper.md, line 30 at r3](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KuMlesaN9HI3kBGK2qJ:-KuMlesaN9HI3kBGK2qK:b-qj7937) ([raw file](https://github.com/pmem/syscall_intercept/blob/6a197f508cf6434c82ef573dd4e570185553f720/src/asm_wrapper.md#L30)):*
> ```Markdown
> particular patched syscall.
> 
> An illustrain of this with two syscalls in a section of intercepted code:
> ```

s/illustrain/illustration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47)*

**Comment by GBuella** [comment]
Review status: 8 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/asm_wrapper.md, line 8 at r3](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KuMl9MPxnMwA_mQ4dpb:-KuTpfzvBr6LSnT4blJJ:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/6a197f508cf6434c82ef573dd4e570185553f720/src/asm_wrapper.md#L8)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

do you mean to say 'due to pesky ABI details'? 
</blockquote></details>

Done.

---

*[src/asm_wrapper.md, line 23 at r3](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KuMlXkMrcfM0NjYIPNJ:-KuTphFW1rLVdzAjJgTc:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/6a197f508cf6434c82ef573dd4e570185553f720/src/asm_wrapper.md#L23)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

s/purpuse/purpose
</blockquote></details>

Done.

---

*[src/asm_wrapper.md, line 30 at r3](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-KuMlesaN9HI3kBGK2qJ:-KuTphqQz_-Ff50P1O7e:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/6a197f508cf6434c82ef573dd4e570185553f720/src/asm_wrapper.md#L30)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

s/illustrain/illustration
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: 8 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47#-:-KuUT1kKzFCaukR-J3au:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 1 of 2 files at r4.
Review status: 9 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/47)*

**Pull request merged**
