### PR TITLE
expect spurious syscalls in intercept_sys_write

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/27)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
LGTM, but please mention in the commit message that it unbreaks code coverage.

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/27#-:-KndmeDZ6euJ2uRJpLIf:bnfp4nl)*

**Comment by GBuella** [comment]
"please mention in the commit message that it unbreaks code coverage reporting."
Done

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/27#-:-Kni3gJvf5piai0oDTpm:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/27#-:-KnnxkwZl0jx0BvacllB:bnfp4nl)*

**Pull request merged**
