### PR TITLE
Refactor syscall logging

### PR DESCRIPTION
**Pull request by GBuella**
* Syscall logging has its own translation unit(s).
 * The syscall argument formats are stored in a table, which
makes them easier to maintain.
 * Removed some libc usages, just to make sure syscall_intercept
is not surprised by something unexpected going on in sprintf calls
(such as libc opening a file to read locales, other tracing, or whatnot).
 * Interpreting error codes returned by syscalls.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/67)

### CODE REVIEW

**Comment by GBuella** [comment]
Mainly based on code in `examples/syscall_logger.c`.

**Comment by krzycz** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/67)*

**Comment by marcinslusarz** [comment]
Reviewed 10 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/intercept_log.c, line 468 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4UdPiuLe-Eezqxt7R:-Kw4UdPiuLe-Eezqxt7S:b-7dzd0) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L468)):*
> ```C
> 		c = print_flag(buffer, c, "O_WRONLY");
> 	if ((flags & (O_WRONLY|O_RDWR)) == 0)
> 		c = print_flag(buffer, c, "O_RDONLY");
> ```

I know this is copied from the old code, but wow, this is ugly.
It should use switch(flags & O_ACCMODE) and compare to each flag.

---

*[src/intercept_log.c, line 685 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4bHQ0sqWn2kJxvQwS:-Kw4bHQ0sqWn2kJxvQwT:b-vde1lj) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L685)):*
> ```C
> 	(void) result;
> 	long flags = desc->args[i];
> 	flags &= ~0x11; /* XXX What are these flags? Undocumented? */
> ```

Why not leave it as is?

---

*[src/intercept_log.c, line 895 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4bju2RKihp3Z0vZqk:-Kw4bju37Pd4i690NTxa:b-lxq4vd) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L895)):*
> ```C
> 	char *c = buffer;
> 
> 	/* prexif: "/lib/libc.so 0x1234 -- " */
> ```

prefix

---

*[src/syscall_formats.c, line 116 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4cJLY9FCIbbJRvs5w:-Kw4cJLY9FCIbbJRvs5x:bb8i8w5) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/syscall_formats.c#L116)):*
> ```C
> 	SARGS(msgrcv, rdec, arg_, arg_, arg_, arg_, arg_),
> 	SARGS(msgctl, rdec, arg_, arg_, arg_),
> 	SARGS(fcntl, rdec, arg_fd, arg_, arg_),
> ```

Shouldn't it use fcntl_args? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/67)*

**Comment by GBuella** [comment]
Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/intercept_log.c, line 468 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4UdPiuLe-Eezqxt7R:-KwAR1mi2SmZlJXkbgQJ:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L468)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I know this is copied from the old code, but wow, this is ugly.
It should use switch(flags & O_ACCMODE) and compare to each flag.
</blockquote></details>

Done.

---

*[src/intercept_log.c, line 685 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4bHQ0sqWn2kJxvQwS:-KwAR4JVyP0bFXIhadXK:b-ci3yqk) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L685)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Why not leave it as is?
</blockquote></details>

I don't know what those values are. I don't know what libc version use them, perhaps all, perhaps not all - I don't know when tests would fail because of this.

---

*[src/intercept_log.c, line 895 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4bju2RKihp3Z0vZqk:-KwAR2o4xw1ip3rM3hgE:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L895)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

prefix
</blockquote></details>

Done.

---

*[src/syscall_formats.c, line 116 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4cJLY9FCIbbJRvs5w:-KwAR3dySbFkl_zo3IIH:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/syscall_formats.c#L116)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Shouldn't it use fcntl_args? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/67)*

**Comment by marcinslusarz** [comment]
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/intercept_log.c, line 685 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4bHQ0sqWn2kJxvQwS:-KwEkSXl2UK_oVQ5ZNHy:b-nuu6hz) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L685)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

I don't know what those values are. I don't know what libc version use them, perhaps all, perhaps not all - I don't know when tests would fail because of this.
</blockquote></details>

"The low byte of flags contains the number of the termination signal sent to the parent when the child dies.  If this signal is specified as anything other than SIGCHLD, then the parent process must specify the __WALL or __WCLONE options when waiting for the child with wait(2).  If no signal is specified, then the parent process is not signaled when the child terminates."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/67)*

**Comment by GBuella** [comment]
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/intercept_log.c, line 685 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4bHQ0sqWn2kJxvQwS:-KwFYTsdGAndiEj_qYtm:bb741c2) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L685)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

"The low byte of flags contains the number of the termination signal sent to the parent when the child dies.  If this signal is specified as anything other than SIGCHLD, then the parent process must specify the __WALL or __WCLONE options when waiting for the child with wait(2).  If no signal is specified, then the parent process is not signaled when the child terminates."
</blockquote></details>

THX!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/67)*

**Comment by GBuella** [comment]
Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/intercept_log.c, line 685 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4bHQ0sqWn2kJxvQwS:-KwK-Qjzf5d1ymvbK9bY:b-896fix) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L685)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

THX!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/67)*

**Comment by krzycz** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/67)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/intercept_log.c, line 685 at r1](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-Kw4bHQ0sqWn2kJxvQwS:-KwK2GhN5r4cf4FVxqN-:b-blvy9h) ([raw file](https://github.com/pmem/syscall_intercept/blob/c98e9f75a45491800425509df9ebce799e699655/src/intercept_log.c#L685)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Since this is a signal you could actually decode it as such. Not necessarily in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/67#-:-KwK3Lj_SMsWZg2bUg0s:bnfp4nl)*

**Pull request merged**
