### PR TITLE
Test with capstone's experimental branch

### PR DESCRIPTION
**Pull request by GBuella**
This PR builds on #61

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/62)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/62)*

**Comment by sarahjelinek** [comment]
Reviewed 8 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/62)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/syscall_intercept/62#-:-KuMkRNJmc2GfO_PEV65:bnfp4nl)*

**Comment by marcinslusarz** [comment]
Why do you want to test with alpha of capstone?
Why not install it to private directory and set PKG_CONFIG_PATH? make install should create proper pc file (If not that's capstone bug, which should be reported).
Also, there's typo in cloned directory.

**Comment by GBuella** [comment]
"Why do you want to test with alpha of capstone?"
To test with a different branch as well, get notified early if we rely on something that is going to change.
"make install should create proper pc file (If not that's capstone bug, which should be reported)." 
It is fixed already, just not merged into this branch yet apparently.https://github.com/aquynh/capstone/pull/912

**Pull request merged**
