### PR TITLE
Fixes to build against Debian Jessie

### PR DESCRIPTION
**Pull request by elboulangero**
Hey, I have a few fixes to build against old Debian Jessie. The last commit of this series is *maybe/probably* not the right thing, it fixes the build, but maybe it breaks the test.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/syscall_intercept/76)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/pmem/syscall_intercept/76)*

**Comment by marcinslusarz** [comment]
I think the last issue should be solved differently - by defining the missing constants if arch==x86_64. This test is probably failing on Jesse now.

**Comment by elboulangero** [comment]
Indeed the test fails on Jessie

**Comment by GBuella** [comment]
True, mlock2 is expected in the tests:
https://github.com/pmem/syscall_intercept/blob/master/test/libcintercept3.log.match#L173

**Comment by smcv** [comment]
> I think the last issue should be solved differently - by defining the missing constants if arch==x86_64

Do you mean like a simpler version of https://github.com/systemd/systemd/blob/master/src/basic/missing_syscall.h and https://github.com/systemd/systemd/blob/master/src/basic/missing.h?

That'll work up to a point, but the test will fail if the running kernel is too old for those syscalls (Linux 3.15 for F_OFD_whatever, Linux 4.4 for mlock2, Linux 3.17 for kexec_file_load). Debian jessie shipped with Linux 3.16.x, so F_OFD_whatever but not the others; current Debian stable (stretch) has 4.9.x. The environment that @elboulangero and I are targeting is actually a Debian derivative with a newer kernel.

Complicating matters, automated build environments frequently use chroots or containers that are run on a kernel that doesn't match the kernel of the target OS. It might be better to use a more lenient test at build-time, that will pass even on relatively old kernels; and then have a more thorough test that can be run in the target environment, perhaps with something like [GNOME-style installed-tests](https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests) or [autopkgtest](https://salsa.debian.org/ci-team/autopkgtest/blob/master/doc/README.package-tests.rst).

I think it would be OK to set a minimum kernel version for full functionality, and expect downstream distributions with older libc/kernel to patch the tests (or even the implementation) according to their minimum supported kernel: that way, downstreams are kept aware of what functionality they're losing.

**Comment by marcinslusarz** [comment]
Yes, I was suggesting something like those "missing*.h" files.

Note that it's only a test and we are not even checking the return value, so it doesn't matter what environment this test is running in.

However, I just noticed that there are already ifdefs in the library, so what Gabor did in #78 is the simplest fix.

IMHO defining missing constants for both library and tests would be cleaner (fewer ifdefs, no special cases in match files) and would help with updating (there's no need to rebuild the library after libc update).

Out of curiosity, can you share how are you going to use syscall_intercept?

**Comment by smcv** [comment]
> Out of curiosity, can you share how are you going to use syscall_intercept?

It's the basis for [libcasefold](https://gitlab.collabora.com/krisman/libcasefold), a library to make filesystem access behave as though the underlying filesystem was case-insensitive and case-preserving (like FAT/NTFS/SMB/HFS+), which is a recurring problem when Windows software is ported to Linux. The author of libcasefold is also working on an in-kernel implementation, but an in-kernel implementation needs a new (or in this case future) kernel, which is not feasible for everyone.

**Comment by marcinslusarz** [comment]
I hope you are aware of how difficult path resolution is... If not, I'd advise to take a look at path resolution in pmemfile.

**Pull request merged**
